// vite.config.js
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// If you renamed mkcert files, adjust the paths below
import fs from "fs";

// Self-signed cert generated by `mkcert localhost 127.0.0.1`
const httpsConfig = {
  key:  fs.readFileSync("../localhost+1-key.pem"),
  cert: fs.readFileSync("../localhost+1.pem"),
};

export default defineConfig({
  plugins: [react()],

  optimizeDeps: {
    exclude: ["lucide-react"],
  },

  /* ── dev server ───────────────────────────────────────── */
  server: {
    https: httpsConfig,          // <-- tells Vite to run on https://localhost:5173
    proxy: {
      // forward API calls to Flask (also https)
      "/authorize": "https://localhost:5000",
      "/oauth2callback": "https://localhost:5000",
      "/profile": "https://localhost:5000",
      "/sync": "https://localhost:5000",
      "/top_senders": "https://localhost:5000",
      "/delete_sender": "https://localhost:5000",
    },
  },
});
